# Generated by Django 5.2.4 on 2025-07-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_finder', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
